...@theme

direction: right

local: CloudShell\nローカル側 {
  class: boundary
  file: ~/upload.txt { class: key }
}

remote: Ubuntuサーバー\nリモート側 {
  class: boundary
  file: ~/jdu-lab/m6/upload.txt { class: key }
}

local.file -> remote.file: upload\nscp local remote:
remote.file -> local.file: download\nscp remote: local
