...@theme

root: ルートディレクトリ / {
  class: boundary
  grid-columns: 3
  home: home {
    class: os
    grid-rows: 4
    ssm: ssm-user { class: identity }
    lab: jdu-lab { class: app }
    m1: m1 { class: app }
    file: errors.txt { class: key }
  }
  etc: etc { class: neutral }
  var: var { class: neutral }
}
